# Generated by Django 3.1.2 on 2020-11-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoulNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='TITLE')),
                ('title_date', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
