# Generated by Django 3.1.2 on 2020-11-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seoilNotice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeoulNotice',
            new_name='SeoilNotice',
        ),
    ]
