# Generated by Django 3.1.2 on 2020-11-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoilNotice', '0002_auto_20201102_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seoilnotice',
            old_name='title_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='seoilnotice',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
