# Generated by Django 3.1.2 on 2020-11-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoilNotice', '0004_eventinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
