# Generated by Django 3.1.2 on 2020-11-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seoilNotice', '0005_academicnotice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademicNotice',
            new_name='BachelorNotice',
        ),
    ]
